target_url: "https://api.example.com"
timeout: 60
follow_redirects: true
verify_ssl: true
scan_jwt: true
scan_headers: true
scan_cors: true
headers:
  User-Agent: "HorseSec-Scanner/1.0.0"
  Accept: "application/json"
  Authorization: "Bearer {{token}}"